### ISSUE TITLE
Improve readme/docs

### ISSUE THREAD

**Issue by wilcotomassen** [sensorlab030/led-wall#5]
* Explain wall geometry
* Make sure all preview shortcuts are documented
* Make sure the delta time is explained
* Build/export process
* libraries

**Comment by agatheblues** [comment]
- Created a simple animation which extends from the BaseAnimation : #7. There is one row and one column of 1px width moving on the grid with various colors, to illustrate how to use the wall geometries. 
- Scaled the source image preview for a BaseAnimation animation
- Update the Readme to add more info for getting started with programming
